networks:
  express-mongo: null
  react-express: null
services:
  client:
    build:
      context: client
      target: development
    container_name: client
    depends_on:
      - server
    environment:
      - DEMO_MODE=1
    networks:
      - react-express
    ports:
      - '3000:3000'
    restart: always
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    container_name: mongo
    image: mongo:4.2.0
    networks:
      - express-mongo
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - ./data:/data
  server:
    build:
      context: server
      target: development
    container_name: server
    depends_on:
      - mongo
    environment:
      - PORT=3000
    expose:
      - 3000
    networks:
      - express-mongo
      - react-express
    restart: always
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules