version: '3'
services:
  # reverse-proxy:
  #   build:
  #     context: ./apps/reverse-proxy
  #     dockerfile: ./apps/reverse-proxy/Dockerfile
  # volumes:
  # depends_on:
  #   - server

  frontend-server:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      args:
        - NODE_ENV=production
        - VITE_API_HOST=http://server:5500
        - VITE_DEV_SERVER_PORT=3000
    expose:
      - 3000
    ports:
      - '3000:3000'
    restart: always

  api-server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017
      - SERVER_PORT=5500
      - SECRET_KEY
    expose:
      - 5500
    ports:
      - '5500:5500'
    restart: always

  mongo:
    container_name: mongo
    image: mongo:6.0.2
    ports:
      - '27017:27017'
