version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      args:
        - NODE_ENV=production
        - VITE_API_HOST=https://datacapture.douglasneuroinformatics.ca:5500/api/v1
        - VITE_DEV_SERVER_PORT=3000
    expose:
      - 3000
    ports:
      - '3000:3000'
    restart: always
  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      args:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017
      - SERVER_PORT=5500
      - SECRET_KEY
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017
      - SERVER_PORT=5500
      - SECRET_KEY
    expose:
      - 5500
    ports:
      - '5500:5500'
    restart: always
  mongo:
    container_name: mongo
    image: mongo:6.0.2
    ports:
      - '27017:27017'
