version: '3'
services:
  caddy:
    image: caddy:2.7
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - HOSTNAME
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - static:/srv
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017
      - API_SERVER_PORT
      - SECRET_KEY
    expose:
      - '${API_SERVER_PORT}'
    ports:
      - '${API_SERVER_PORT}:${API_SERVER_PORT}'
    restart: always
  api-docs:
    image: redocly/redoc
    environment:
      - SPEC_URL=https://$HOSTNAME/api/spec.json"
    ports:
      - "8080:80"
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
      args:
        - VITE_API_HOST
        - VITE_DOCS_URL
        - VITE_LICENSE_URL
        - VITE_GITHUB_REPO_URL
        - VITE_CONTACT_EMAIL
    tty: true
    volumes:
      - static:/app
    restart: always
  mongo:
    container_name: mongo
    image: mongo:6.0.2
    expose:
      - 27017
volumes:
  static:
