version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017
      - API_SERVER_PORT
      - SECRET_KEY
    expose:
      - '${API_SERVER_PORT}'
    ports:
      - '${API_SERVER_PORT}:${API_SERVER_PORT}'
    restart: always
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
      args:
        - VITE_API_HOST=https://datacapture.douglasneuroinformatics.ca/api
        - VITE_DOCS_URL
        - VITE_LICENSE_URL
        - VITE_GITHUB_REPO_URL
        - VITE_CONTACT_EMAIL
    environment:
      - NODE_ENV=production
      - WEB_SERVER_PORT
    expose:
      - '${WEB_SERVER_PORT}'
    ports:
      - '${WEB_SERVER_PORT}:${WEB_SERVER_PORT}'
    restart: always
  mongo:
    container_name: mongo
    image: mongo:6.0.2
    expose:
      - 27017
