version: '3'
name: open-data-capture
volumes:
  caddy_data:
  mongo_data:
services:
  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    ports:
      - '5500:80'
    environment:
      - SITE_ADDRESS
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
  api:
    image: ghcr.io/douglasneuroinformatics/data-capture-api:latest
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017
      - GATEWAY_BASE_URL=https://demogateway.opendatacapture.org
      - GATEWAY_API_KEY
      - GATEWAY_ENABLED
      - GATEWAY_REFRESH_INTERVAL
      - SECRET_KEY
    expose:
      - 80
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    ports:
      - '3500:80'
    expose:
      - 80
    environment:
      - GATEWAY_BASE_URL=https://demogateway.opendatacapture.org
  playground:
    build:
      context: .
      dockerfile: ./apps/playground/Dockerfile
    ports:
      - '3750:80'
    expose:
      - 80
  web:
    image: ghcr.io/douglasneuroinformatics/data-capture-web:latest
    build:
      args:
        VITE_API_BASE_URL: /api
      context: .
      dockerfile: ./apps/web/Dockerfile
    environment:
      - CONTACT_EMAIL
      - DOCS_URL
      - GITHUB_REPO_URL
      - LICENSE_URL
      - GATEWAY_ENABLED
    expose:
      - 80
  mongo:
    image: mongo:6.0.2
    expose:
      - 27017
    volumes:
      - mongo_data:/data/db
