version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    container_name: client
    depends_on:
      - server
    environment:
      - DEMO_MODE=1
      - NEXT_PUBLIC_API_HOST=http://server:5500
    expose:
      - 3000
    networks:
      - client-server
    ports:
      - '3000:3000'
    restart: always
  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    container_name: server
    depends_on:
      - mongo
    environment:
      - NODE_ENV=demo
      - MONGO_URI=mongodb://mongo:27017
      - SERVER_PORT=5500
    expose:
      - 5500
    networks:
      - server-mongo
      - client-server
    ports:
      - '5500:5500'
    restart: always
  mongo:
    container_name: mongo
    image: mongo:6.0.2
    networks:
      - server-mongo
    ports:
      - '27017:27017'
networks:
  server-mongo: null
  client-server: null