version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      args:
        - NODE_ENV=production
        - VITE_API_HOST=https://datacapture.douglasneuroinformatics.ca/api
        - VITE_DEV_SERVER_PORT=3000
      tags:
        - "ghcr.io/douglasneuroinformatics/douglasdatacaptureplatform-client:0.01"
        - "ghcr.io/douglasneuroinformatics/douglasdatacaptureplatform-client:latest"
    expose:
      - 3000
    ports:
      - '3000:3000'
    restart: always
  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      args:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017
      - SERVER_PORT=5500
      - SECRET_KEY
      tags:
        - "ghcr.io/douglasneuroinformatics/douglasdatacaptureplatform-server:0.01"
        - "ghcr.io/douglasneuroinformatics/douglasdatacaptureplatform-server:latest"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017
      - SERVER_PORT=5500
      - SECRET_KEY
    expose:
      - 5500
    ports:
      - '5500:5500'
    restart: always

  # @note How to create a new mongo image containing the instantiated database.
  # 1. Login to github repository using `docker login` cf. https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
  # 2. retrieve server container using `docker ps`
  # 3. do `docker exec -it <SERVER CONTAINER> /bin/bash`
  # 4. run `node ./apps/server/dist/cli.js init-demo`
  # 5. retrieve mongo container using `docker ps`
  # 6. `docker commit <MONGO CONTAINER> ghcr.io/douglasneuroinformatics/douglasdatacaptureplatform-mongo:latest`
  # 7. `docker commit <MONGO CONTAINER> ghcr.io/douglasneuroinformatics/douglasdatacaptureplatform-mongo:<VERSION>`
  # 8. `docker push ghcr.io/douglasneuroinformatics/douglasdatacaptureplatform-mongo:latest`
  # 9. `docker push ghcr.io/douglasneuroinformatics/douglasdatacaptureplatform-mongo:<VERSION>`
  # @note push other images as well
  # 10. `docker push ghcr.io/douglasneuroinformatics/douglasdatacaptureplatform-client:latest`
  # 11. `docker push ghcr.io/douglasneuroinformatics/douglasdatacaptureplatform-client:<VERSION>`
  # 12. `docker push ghcr.io/douglasneuroinformatics/douglasdatacaptureplatform-server:latest`
  # 13. `docker push ghcr.io/douglasneuroinformatics/douglasdatacaptureplatform-server:<VERSION>`
  mongo:
    container_name: mongo
    image: mongo:6.0.2
    ports:
      - '27017:27017'
