version: '3'
name: open-data-capture
volumes:
  caddy_data:
  mongo_config:
  mongo_data:
services:
  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS:-localhost:80}
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
  api:
    image: ghcr.io/douglasneuroinformatics/open-data-capture-api:${RELEASE_CHANNEL}
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    depends_on:
      - mongo
    environment:
      - ESBUILD_BINARY_PATH=dist/bin/esbuild
      - GATEWAY_INTERNAL_NETWORK_URL=http://gateway:80
      - GATEWAY_SITE_ADDRESS=${GATEWAY_SITE_ADDRESS:-localhost:3500}
      - GATEWAY_BASE_URL
      - MONGO_REPLICA_SET=rs0
      - MONGO_RETRY_WRITES=true
      - MONGO_WRITE_CONCERN=majority
      - MONGO_DIRECT_CONNECTION=true
      - MONGO_URI=mongodb://mongo:27017
      - NODE_ENV=production
      - DEBUG
      - GATEWAY_API_KEY
      - GATEWAY_ENABLED
      - GATEWAY_REFRESH_INTERVAL
      - SECRET_KEY
      - VERBOSE
    expose:
      - 80
  gateway:
    image: ghcr.io/douglasneuroinformatics/open-data-capture-gateway:${RELEASE_CHANNEL}
    build:
      args:
        GATEWAY_DATABASE_FILEPATH: /app/gateway.db
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    ports:
      - '3500:80'
    expose:
      - 80
    environment:
      - NODE_ENV=production
      - GATEWAY_API_KEY
  playground:
    image: ghcr.io/douglasneuroinformatics/open-data-capture-playground:${RELEASE_CHANNEL}
    build:
      context: .
      dockerfile: ./apps/playground/Dockerfile
    ports:
      - '3750:80'
    expose:
      - 80
  web:
    image: ghcr.io/douglasneuroinformatics/open-data-capture-web:${RELEASE_CHANNEL}
    build:
      args:
        VITE_API_BASE_URL: /api
      context: .
      dockerfile: ./apps/web/Dockerfile
    environment:
      - CONTACT_EMAIL
      - DOCS_URL
      - GITHUB_REPO_URL
      - LICENSE_URL
      - GATEWAY_ENABLED
    expose:
      - 80
  mongo:
    image: mongo:${MONGODB_VERSION}
    command: ['--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
    expose:
      - 27017
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - mongo_config:/data/configdb
      - mongo_data:/data/db
