packages:
  - 'apps/*'
  - 'packages/*'
  - 'runtime/*'
  - 'testing/*'
  - 'vendor/**/*'
catalog:
  '@microsoft/api-extractor': ^7.47.6
  'prisma': '^5.18.0'
  '@prisma/client': '^5.18.0'
  'react-i18next': '^14.1.3'
  'i18next': '^23.14.0'
catalogs:
  'esbuild':
    esbuild: 0.23.x
    esbuild-wasm: 0.23.x
