catalog:
  '@casl/ability': ^6.7.1
  '@casl/prisma': ^1.4.1
  '@douglasneuroinformatics/libjs': latest
  '@douglasneuroinformatics/libstats': latest
  '@douglasneuroinformatics/libui': latest
  '@douglasneuroinformatics/libui-form-types': latest
  '@microsoft/api-extractor': ^7.47.6
  '@prisma/client': ^5.18.0
  '@testing-library/dom': '^10.4.0'
  '@testing-library/jest-dom': ^6.5.0
  '@testing-library/react': ^16.0.1
  '@testing-library/user-event': ^14.5.2
  esbuild: 0.23.x
  esbuild-wasm: 0.23.x
  happy-dom: ^15.7.4
  nodemon: ^3.1.4
  prisma: ^5.18.0
  tsx: 4.8.2
packages:
  - apps/*
  - packages/*
  - runtime/*
  - testing/*
  - vendor/**/*
