name: Bug
description: Report a bug
labels: ["Bug"]
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
    placeholder: |
      Example: If there are errors in a form and the user changes the language, the error messages are not translated into the new language.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
    placeholder: |
      Example: If a user changes languages, any error messages in the form should be translated into the new language.
  validations:
    required: true
- type: dropdown
  id: browsers
  attributes:
    label: Browser
    description: What browsers are you seeing the problem on?
    multiple: true
    options:
      - Firefox
      - Chrome
      - Safari
      - Edge
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      Example:
      1. Open a form with required fields
      2. Attempt to submit the empty form
      3. Change the language
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Details
  validations:
    required: false
- type: dropdown
  id: priority
  attributes:
    label: Priority
    options:
      - High
      - Medium
      - Low
  validations:
    required: true