name: Enhancement
description: Request a change to an existing feature in the codebase
labels: ["Enhancement"]
assignees:
  - joshunrau
body:
- type: textarea
  attributes:
    label: Current Implementation and Limitations
    description: Describe current state of the feature in question, particularly any limitations
  validations:
    required: true
- type: dropdown
  attributes:
    label: Associated Application Components
    description: Select the application components related to this feature
    multiple: true
    options:
      - Client
      - Server
  validations:
    required: true
- type: textarea
  attributes:
    label: Proposed Solution
    description: Describe the enhancement in detail and explain how it will address the limitations/problems described above
  validations:
    required: true
- type: dropdown
  id: difficulty
  attributes:
    label: Estimated Difficulty
    description: Please select low for trivial changes (e.g., changing the size of a card on the overview page), medium for significant non-systematic changes (e.g., adding a new type of data to the overview page), and high for systematic changes (e.g., rewriting the overview page to include graphs with the standard deviation instead of a simple counter). If you are unable to estimate the difficulty of an enhancement, please leave this field blank.
    options:
      - High
      - Medium
      - Low
  validations:
    required: false
- type: dropdown
  id: priority
  attributes:
    label: Priority
    options:
      - High
      - Medium
      - Low
  validations:
    required: true
