name: Enhancement
description: Request a change to an existing feature in the codebase
labels: ["Enhancement"]
body:
- type: textarea
  attributes:
    label: Current Implementation
    description: Please briefly describe current state of the feature in question, in particular the limitations/problems of the current solution
  validations:
    required: true
- type: dropdown
  attributes:
    label: Associated Application Components
    description: Please select all application components that this enhancement concerns
    multiple: true
    options:
      - Client
      - Server
  validations:
    required: true
- type: textarea
  attributes:
    label: Proposed Changes
    description: Please describe the enhancement in detail, explaining how this change will solve the above limitations
  validations:
    required: true
- type: dropdown
  id: priority
  attributes:
    label: Priority
    options:
      - High
      - Medium
      - Low
  validations:
    required: true
