name: Feature
description: Request a new feature be implemented in the codebase
labels: ["Feature"]
assignees:
  - joshunrau
body:
- type: textarea
  attributes:
    label: Description
    description: Please describe the feature in detail
  validations:
    required: true
- type: dropdown
  id: difficulty
  attributes:
    label: Estimated Difficulty
    description: Please select low for simple, relatively isolated features (estimated time to implement of 2 hours or less; e.g., a new variant of form field), medium for straightforward features (estimated time to implement of 8 hours or less), and high for features that will require systematic changes across the entire codebase (estimated time to implement of 8 hours or more).
    options:
      - High
      - Medium
      - Low
  validations:
    required: false
- type: dropdown
  id: priority
  attributes:
    label: Priority
    options:
      - High
      - Medium
      - Low
  validations:
    required: true
