openapi: '3.0.0'
info:
  version: 1.0.0
  title: Douglas Data Capture Platform
  description: This is a REST API for the Douglas Data Capture Platform
  license:
    name: Apache 2.0
    url: https://www.gnu.org/licenses/gpl-3.0-standalone.html
paths:
  /hello:
    get:
      summary: test route
      description: This route is a test