name: Main
on:
  push:
    branches: ['main']
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./apps/api/Dockerfile
            image: ghcr.io/douglasneuroinformatics/open-data-capture-api:latest
          - dockerfile: ./apps/gateway/Dockerfile
            image: ghcr.io/douglasneuroinformatics/open-data-capture-gateway:latest
          - dockerfile: ./apps/playground/Dockerfile
            image: ghcr.io/douglasneuroinformatics/open-data-capture-playground:latest
          - dockerfile: ./apps/web/Dockerfile
            image: ghcr.io/douglasneuroinformatics/open-data-capture-web:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Environment
        run: ./scripts/generate-env.sh
      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and Push Docker Images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
