name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
jobs:
  build:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:7.0
        ports:
          - 27017:27017
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get Package Metadata
        run: |
          echo "BUN_VERSION=$(cat package.json | jq .packageManager | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')" >> $GITHUB_ENV
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Setup Environment
        run: bun generate:env
      - name: Install Dependencies
        run: bun install
      - name: Lint
        run: bun run lint
      - name: Build
        run: bun run build
      - name: Test
        run: bun run test
        env:
          TERM: xterm
