name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
defaults:
  run:
    shell: bash
permissions:
  contents: read
  packages: write
jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run Script
        uses: actions/github-script@v7
        with:
          script: |
            const { getLatestVersion } = await import('${{ github.workspace }}/.github/scripts/lib.js');
            await getLatestVersion();
