name: build
on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - "client/**"
      - "server/**"
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: node:lts-buster-slim
    env:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017
    services:
      mongo:
        image: mongo:6.0.2
        ports:
          - 27017:27017
    steps:
      - name: download code
        uses: actions/checkout@v3
      - name: install node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci --prefix server 
      - name: run tests
        run: npm test --prefix server
