name: main
on:
  pull_request:
    types:
      - opened
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SITE_ADDRESS: localhost:3000
      SECRET_KEY: secret-key
      MONGO_URI: mongodb://mongo:27017
      VITE_CONTACT_EMAIL: postmaster@example.org
      VITE_DOCS_URL: https://google.com
      VITE_GITHUB_REPO_URL: https://github.com/DouglasNeuroInformatics/DouglasDataCapturePlatform
      VITE_LICENSE_URL: https://www.gnu.org/licenses/agpl-3.0.en.html
      API_DEV_SERVER_PORT: 5500
      WEB_DEV_SERVER_PORT: 3000
    services:
      mongo:
        image: mongo:6.0.2
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '18.x'
      - run: yarn install --frozen-lockfile
      - run: yarn turbo run lint
      - run: yarn turbo run test