name: Deploy marketing website to GitHub Pages
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - 'marketing/**'
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '20.5'
      - name: Install Dependencies
        run: npm ci
      - name: Build Site
        run: npm run build --workspace marketing
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'marketing/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
