name: Pull Request
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      mongodb_version: ${{ steps.define.outputs.MONGODB_VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - id: define
        run: |
          cat .env.template | grep MONGODB_VERSION >> "$GITHUB_OUTPUT"
  build:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    needs: configure
    services:
      mongo:
        image: mongo:${{needs.configure.outputs.mongodb_version}}
        ports:
          - 27017:27017
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'
      - name: Cache Cypress Binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Setup Environment
        run: pnpm generate:env
      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm cy:install
      - name: Verify Cypress
        env:
          CI: 1
        run: |
          pnpm exec cypress verify
          pnpm exec cypress info
          pnpm exec cypress version
          pnpm exec cypress version --component package
          pnpm exec cypress version --component binary
          pnpm exec cypress version --component electron
          pnpm exec cypress version --component node
      - name: Lint
        run: pnpm run lint
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run test
        env:
          TERM: xterm
