name: Release
on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./apps/api/Dockerfile
            image: ghcr.io/douglasneuroinformatics/data-capture-api
          - dockerfile: ./apps/web/Dockerfile
            image: ghcr.io/douglasneuroinformatics/data-capture-web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CONTACT_EMAIL=support@douglasneuroinformatics.ca
            DOCS_URL=https://opendatacapture.org/docs
            GITHUB_REPO_URL=https://github.com/DouglasNeuroInformatics/OpenDataCapture
            LICENSE_URL=https://www.gnu.org/licenses/agpl-3.0.en.html
            VITE_API_BASE_URL=/api
  