name: Test Server
on:
  push:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v3
      - name: install node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: ls
